#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_api.sh"

# Set good defaults to allow script to be run by hand
DOCKER_REPO=${DOCKER_REPO:-"mitigram/portainer-ce"}
BUILDX_PLATFORMS=${BUILDX_PLATFORMS:-"linux/amd64"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

# Base image to follow
BASE_IMAGE=portainer/portainer-ce

# List of tags to build, default is latest and all pure versions
TAGS=${TAGS:-$(img_tags \
                --filter '^([0-9]+(\.[0-9]+)+|latest)$' \
                --verbose \
                -- \
                "$BASE_IMAGE" | sort)}

# Login at the Docker hub to be able to access info about the image.
token=$(img_auth "$DOCKER_REPO")

# For all tags of the original image (as in library image) that this image
# builds upon, rebuild only if relevant. We use the OCI revision annotation to
# store/detect whenever it is necessary to rebuild.
for tag in $TAGS; do
  # Get the revision out of the org.opencontainers.image.revision label,
  # this will be the label where we store information about this repo (it
  # cannot be the tag, since we tag as the base image).
  revision=$( img_labels --verbose --token "$token" -- "$DOCKER_REPO" "$tag" |
                grep "^org.opencontainers.image.revision" |
                sed -E 's/^org.opencontainers.image.revision=(.+)/\1/')
  # If the revision is different from the source commit (including empty,
  # which will happen when our version of the image does not already
  # exist), build the image, making sure we label with the git commit sha
  # at the org.opencontainers.image.revision OCI label, but using the same
  # tag as the library image.
  if [ "$revision" != "$SOURCE_COMMIT" ]; then
    img=$(img_canonicalize "${DOCKER_REPO}:$tag")
    if [ "${DOCKER_BUILDKIT:-0}" = "1" ]; then
      echo "============== No $img at $SOURCE_COMMIT, building with BuildKit" >&2
      if docker buildx build \
          --build-arg PORTAINER_VERSION="$tag" \
          --tag "$img" \
          --label "org.opencontainers.image.revision=$SOURCE_COMMIT" \
          --platform "$BUILDX_PLATFORMS" \
          --load \
          . >&2; then
        echo "$tag"
      else
        exit "$?"
      fi
    else
      echo "============== No $img at $SOURCE_COMMIT, legacy build" >&2
      if docker build \
          --build-arg PORTAINER_VERSION="$tag" \
          --tag "$img" \
          --label "org.opencontainers.image.revision=$SOURCE_COMMIT" \
          . >&2; then
        echo "$tag"
      else
        exit "$?"
      fi
    fi
  fi
done