#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

# Set good defaults to allow script to be run by hand
DOCKER_REPO=${DOCKER_REPO:-"mitigram/portainer-ce"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

# Base image to follow
BASE_IMAGE=portainer/portainer-ce

for tag in $(img_tags \
                --filter '^([0-9]+(\.[0-9]+)+|latest)$' \
                --verbose \
                -- \
                "$BASE_IMAGE" | sort); do
  if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
    echo "============== Pushing ${DOCKER_REPO}:$tag"
    docker push "${DOCKER_REPO}:$tag"
  else
    echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
  fi
done