#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_api.sh"

# Set good defaults to allow script to be run by hand
DOCKER_REPO=${DOCKER_REPO:-"mitigram/portainer-ce"}
SOURCE_COMMIT=${SOURCE_COMMIT:-$(git log --no-decorate|grep '^commit'|head -n 1| awk '{print $2}')}

# Base image to follow
BASE_IMAGE=portainer/portainer-ce

# List of tags to push, default is latest and all pure versions
TAGS=${TAGS:-$(img_tags \
                --filter '^([0-9]+(\.[0-9]+)+|latest)$' \
                --verbose \
                -- \
                "$BASE_IMAGE" | sort)}

for tag in $TAGS; do
  img=$(img_canonicalize "${DOCKER_REPO}:$tag")
  if docker image inspect "$img" >/dev/null 2>&1; then
    echo "============== Pushing $img" >&2
    if docker push "$img" >&2; then
      echo "$tag"
    else
      exit "$?"
    fi
  else
    echo "!!!!!!!!!!!!!! $img was not built, cannot push!" >&2
  fi
done