name: docker

on:
  push:
    branches:
      - 'main'
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hub:
    name: DockerHub
    uses: ./.github/workflows/_image.yml
    with:
      registry: docker.io
      push: false
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  ghcr:
    name: GHCR
    uses: ./.github/workflows/_image.yml
    with:
      registry: ghcr.io
      push: false
    secrets:
      username: ${{ secrets.GH_USERNAME }}
      password: ${{ secrets.GH_TOKEN }}

  description:
    runs-on: ubuntu-latest
    name: DockerHub Description
    needs:
      - hub
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mitigram/portainer-ce
