name: docker

on:
  push:
    branches:
      - 'main'
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        # Login using the default repository token
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/mitigram/portainer-ce
          SOURCE_COMMIT: ${{ github.sha }}
          DOCKER_BUILDKIT: "1"
        run: ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/mitigram/portainer-ce
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/mitigram/portainer-ce
          SOURCE_COMMIT: ${{ github.sha }}
          DOCKER_BUILDKIT: "1"
        run: ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/mitigram/portainer-ce
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
      -
        # Note: This uses the password, not the token as this action would
        # otherwise not work.
        name: Update repo description at Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mitigram/portainer-ce